/*This creates an array of objects called arr. Each object has a single key-value pair, 
where the key is list and the value is a string.*/
const arr = [
    {
        list: "Select"
    },
    {
        list: "Yes"
    },
    {
        list: "Probably not"
    }
]


/*This defines a stateless functional component called DropDown that returns a select element 
with options generated by mapping over the arr array. For each object in the array, it generates 
an option element with the list value as its text content. */

const DropDown = () =>(
    <select>
        {arr.map((res, index) =>(
            <option key={index}>
                {res.list}
            </option>
        ))}
    </select>
)

/* This defines another stateless functional component called App that renders a h2 element with 
the text "Should you use the dropdown?" and the DropDown component. */

const App = () =>(
    <div className="container">
    <h2>Should you use the dropdown?</h2>
    <DropDown />
    </div>
)

/* This initializes a new Root for the React application and renders the App component into a root 
element with the ID "root" using the render method. */

const rootElement = ReactDOM.createRoot(document.getElementById("root"));
rootElement.render(<App />);